In [1]:
numbers = [1, 2, 3]

In [2]:
numbers * 2

[1, 2, 3, 1, 2, 3]

In [3]:
numbers = [1, 2, 3]
numbers * 2

[1, 2, 3, 1, 2, 3]

In [4]:
[x * 2 for x in numbers]

[2, 4, 6]

In [5]:
import numpy as np

numbers = np.array([1, 2, 3])

In [6]:
numbers * 2

array([2, 4, 6])

In [7]:
numbers = [[1, 2], [3, 4]]

In [8]:
ones = [[1] * 10 for _ in range(10)]

In [9]:
numbers = [[1, 2], [3, 4]]
numbers_np = np.array(numbers)

In [10]:
zeros = np.zeros((10, 10))  # 全ての要素が0の10x10の二次元配列
ones = np.ones((10, 10))  # 全ての要素が1の10x10の二次元配列
twos = np.full((10, 10), 2)  # 全ての要素が2の10x10の二次元配列

In [11]:
print(np.zeros((3)))  # 全て0で初期化
print(np.ones((3)))  # 全て1で初期化
print(np.full((3), 10.0))  # 全て同じ値 (10.0)で初期化

[0. 0. 0.]
[1. 1. 1.]
[10. 10. 10.]


In [12]:
print(np.arange(10))  # [0, 10)について1刻み
print(np.arange(5, 10))  # [5, 10)について1刻み
print(np.arange(0, 10, 2))  # [0, 10)について2刻み
print(np.arange(9, -1, -1))  # 9以下かつ-1より大きい整数を列挙

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [13]:
print(np.linspace(0, 10, 5))  # 両端点を含み0.0と10.0の間を5分割
print(np.linspace(0, 10, 5, endpoint=False)) # 上端を含まず、0.0と10.0の間を5分割

[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]


In [14]:
arr = np.geomspace(1, 10, 4)  # を初項とし、10で終わる5項の等比数列
print(arr)
print(np.log(arr))  # 対数を取ると等差数列になっている

[ 1.          2.15443469  4.64158883 10.        ]
[0.         0.76752836 1.53505673 2.30258509]


In [15]:
arr = np.logspace(1, 10, 4, base=2)  # 2^1から2^10までを4項で結ぶ等比数列
print(arr)
print(np.log2(arr))  # log2を取ると、等差数列になっている

[   2.   16.  128. 1024.]
[ 1.  4.  7. 10.]


In [16]:
ix = np.arange(0, 3)
iy = np.arange(0, 5)
ix, iy = np.meshgrid(ix, iy)  # ix, iyの順序に注意
print(ix)
print(iy)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [17]:
ix, iy = np.mgrid[:5, :3]  # 軸の順序に注意
print(ix)
print(iy)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [18]:
numbers = np.array([1, 2, 3])
print(numbers)

[1 2 3]


In [19]:
numbers.dtype

dtype('int64')

In [20]:
ones = np.ones((4, 5, 6))
ones.shape

(4, 5, 6)

In [21]:
ones.ndim

3

In [22]:
numbers = np.array([1, 2, 3], dtype="float32")

In [23]:
numbers = np.array([1, 2, 3])  # int32型
numbers = numbers.astype("float32")  # 型をfloat32に変更

In [24]:
arr2d = np.array([[1, 2], [3, 4]])
print("0th column:", arr2d[:, 0])
print("1st row:", arr2d[1, :])

0th column: [1 3]
1st row: [3 4]


In [25]:
# 例1: 単一要素の書き換え
arr2d = np.array([[1, 2], [3, 4]])
arr2d[0, 0] = 2
print(arr2d)

[[2 2]
 [3 4]]


In [26]:
# 例2: 部分配列の書き換え
arr2d = np.array([[1, 2], [3, 4]])
arr2d[0, :] = 10
print(arr2d)

[[10 10]
 [ 3  4]]


In [27]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = arr2d.reshape((4))
print(arr1d)

[1 2 3 4]


In [28]:
arr2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Before:\n", arr2x3)
arr3x2 = arr2x3.reshape((3, -1))
print("After:\n", arr3x2)

Before:
 [[1 2 3]
 [4 5 6]]
After:
 [[1 2]
 [3 4]
 [5 6]]


In [29]:
arr2d = np.array([[1, 2], [3, 4]])
print("reshape:", arr2d.reshape((-1)))
print("flatten:", arr2d.flatten())
print("ravel:", arr2d.ravel())

reshape: [1 2 3 4]
flatten: [1 2 3 4]
ravel: [1 2 3 4]


In [30]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d_rs = arr2d.reshape((-1))
arr1d_fl = arr2d.flatten()
arr1d_rv = arr2d.ravel()
arr2d[0, 0] = 2
print("reshape:", arr1d_rs)
print("flatten:", arr1d_fl)
print("ravel:", arr1d_rv)

reshape: [2 2 3 4]
flatten: [1 2 3 4]
ravel: [2 2 3 4]


In [31]:
arr2d = np.array([[1, 2], [3, 4]])
print("reshape:", arr2d.reshape((2, -1, 2)).shape)
print("None:", arr2d[:, None].shape)
print("newaxis", arr2d[:, np.newaxis].shape)

reshape: (2, 1, 2)
None: (2, 1, 2)
newaxis (2, 1, 2)


In [32]:
a = np.array([1, 2])
print(a + 1)  # array([2, 3])

[2 3]


In [33]:
a = np.array([1, 2])
b = np.array([3, 4])
print(a + b)  # array([4, 6])

[4 6]


In [34]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.dot(a, b))

11


In [35]:
print(a @ b)

11


In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.cross(a, b))

[-3  6 -3]


In [37]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.cross(a, b))

-2


In [38]:
A = np.array([[1, 2], [3, 4]], dtype="double")
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [39]:
# 行列のランク
np.linalg.matrix_rank(A)  # 2

2

In [40]:
# 行列式
np.linalg.det(A)

-2.0000000000000004

In [41]:
A = np.array([[1, 2], [2, 4]], dtype="double")
try:
    np.linalg.inv(A)
except Exception as e:
    print("Exception: {:s}".format(type(e).__name__))
    print("Message: {:s}".format(str(e)))

Exception: LinAlgError
Message: Singular matrix


In [42]:
# この行列は特異行列
A = np.array([[1, 2], [2, 4]], dtype="double")
pinvA = np.linalg.pinv(A)
print("- pinv(A) @ A")
print(pinvA @ A)
print("")
print("- A @ pinv(A) @ A")
print(A @ pinvA @ A)

- pinv(A) @ A
[[0.2 0.4]
 [0.4 0.8]]

- A @ pinv(A) @ A
[[1. 2.]
 [2. 4.]]


In [43]:
A = np.array([[1, 2], [3, 4]])
b = np.array([1, 1])
x = np.linalg.solve(A, b)
print(x)

[-1.  1.]


In [44]:
import scipy as sp
import scipy.linalg

In [45]:
A = np.array([[1, 2], [3, 4]])
lu, piv = sp.linalg.lu_factor(A)

In [46]:
b1 = np.array([1, 1])
x1 = sp.linalg.lu_solve((lu, piv), b1)
print(x1)

[-1.  1.]


In [47]:
b2 = np.array([2, 2])
x2 = sp.linalg.lu_solve((lu, piv), b2)
print(x2)

[-2.  2.]


In [48]:
A = np.array([[1, 2], [2, 1]], dtype="double")
eigval, eigvec = np.linalg.eig(A)
print(eigval)
print(eigvec)

[ 3. -1.]


[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
